---
services:
  gotify:
    image: gotify/server
    container_name: gotify
    volumes:
      - ./:/app/data
    restart: unless-stopped
    command:
      - "--entryPoints.https-external.transport.respondingTimeouts.readTimeout=420"
      - "--entryPoints.https-external.transport.respondingTimeouts.writeTimeout=420"
      - "--entryPoints.https-external.transport.respondingTimeouts.idleTimeout=420"
    security_opt:
      - no-new-privileges:true
    networks:
      public:
    environment:
      - TZ=Europe/Vienna
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.gotify.entrypoints=http"
      - "traefik.http.routers.gotify.rule=Host(`gotify.ahwz.dev`)"
      - "traefik.http.middlewares.gotify-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.gotify.middlewares=gotify-https-redirect"
      - "traefik.http.routers.gotify-secure.entrypoints=https"
      - "traefik.http.routers.gotify-secure.rule=Host(`gotify.ahwz.dev`)"
      - "traefik.http.routers.gotify-secure.tls=true"
      - "traefik.http.routers.gotify-secure.service=gotify"
      - "traefik.http.services.gotify.loadbalancer.server.port=80"
      - "traefik.docker.network=public"

networks:
  public:
    external: true
