---
services:
  nextcloud:
    image: lscr.io/linuxserver/nextcloud:latest
    container_name: nextcloud
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Vienna
    volumes:
      - /home/hazardoussheep/projects/nextcloud/appdata:/config
      - /home/hazardoussheep/projects/nextcloud/data:/data
    # - /home/hazardoussheep/youtube-dl:/youtube
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '3.0'       # never takes your whole machine
          memory: 4G        # adjust to your available RAM
        reservations:
          cpus: '0.5'
          memory: 512M
    networks:
      - public
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nextcloud.entrypoints=http"
      - "traefik.http.routers.nextcloud.rule=Host(`nextcloud.ahwz.dev`)"
      - "traefik.http.middlewares.nextcloud-https-redirect.redirectscheme.scheme=websecure"
      - "traefik.http.routers.nextcloud.middlewares=nextcloud-https-redirect"
      - "traefik.http.routers.nextcloud-secure.entrypoints=https"
      - "traefik.http.routers.nextcloud-secure.rule=Host(`nextcloud.ahwz.dev`)"
      - "traefik.http.routers.nextcloud-secure.tls=true"
      - "traefik.http.routers.nextcloud-secure.service=nextcloud"
      - "traefik.http.services.nextcloud.loadbalancer.server.port=80"
      - "traefik.docker.network=public"

networks:
  public:
    external: true

