---
services:
  diun:
    image: crazymax/diun:latest
    container_name: diun
    command: serve
    volumes:
      - "~/projects/diun/data:/data"
      - "/var/run/docker.sock:/var/run/docker.sock"
    environment:
      - "TZ=Europe/Vienna"
      - "LOG_LEVEL=info"
      - "DIUN_WATCH_WORKERS=20"
      - "DIUN_WATCH_SCHEDULE=0 0 * * 0"
      - "DIUN_WATCH_JITTER=30s"
      - "DIUN_WATCH_RUNONSTARTUP=true"
      - "DIUN_PROVIDERS_DOCKER=true"
      - "DIUN_PROVIDERS_DOCKER_WATCHBYDEFAULT=true"

      - "DIUN_NOTIF_GOTIFY_ENDPOINT=${GOTIFY_ENDPOINT}"
      - "DIUN_NOTIF_GOTIFY_TOKEN=${GOTIFY_TOKEN}" # get your token from Gotify UI
      - "DIUN_NOTIF_GOTIFY_PRIORITY=1"
      - "DIUN_NOTIF_GOTIFY_TIMEOUT=10s"

      - "DIUN_NOTIF_DISCORD_WEBHOOKURL=${DISCORD_WEBHOOK_URL}" # change to your webhook
      # - "DIUN_NOTIF_DISCORD_MENTIONS" # (comma separated)
      - "DIUN_NOTIF_DISCORD_RENDERFIELDS=true"
      - "DIUN_NOTIF_DISCORD_TIMEOUT=10s"
      # - "DIUN_NOTIF_DISCORD_TEMPLATEBODY"

    labels:
      - "diun.enable=true"
    restart: always
