services:
  booklore:
    image: booklore/booklore:latest
    # Alternative: Use GitHub Container Registry
    # image: ghcr.io/booklore-app/booklore:latest
    container_name: booklore
    environment:
      - USER_ID=${APP_USER_ID}
      - GROUP_ID=${APP_GROUP_ID}
      - TZ=${TZ}
      - DATABASE_URL=${DATABASE_URL}
      - DATABASE_USERNAME=${DB_USER}
      - DATABASE_PASSWORD=${DB_PASSWORD}
      - BOOKLORE_PORT=${BOOKLORE_PORT}
    depends_on:
      mariadb:
        condition: service_healthy
    ports:
      - "${BOOKLORE_PORT}:${BOOKLORE_PORT}"
    networks:
      - public
    volumes:
      - ~/projects/booklore/data:/app/data
      - ~/projects/booklore/books:/books
      - ~/projects/booklore/bookdrop:/bookdrop
    healthcheck:
      test: wget -q -O - http://localhost:${BOOKLORE_PORT}/api/v1/healthcheck
      interval: 60s
      retries: 5
      start_period: 60s
      timeout: 10s
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=public"
      - "traefik.http.routers.booklore.entrypoints=http"
      - "traefik.http.routers.booklore.rule=Host(`booklore.ahwz.dev`)"
      - "traefik.http.middlewares.booklore-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.booklore.middlewares=it-tools-https-redirect"
      - "traefik.http.routers.booklore-secure.entrypoints=https"
      - "traefik.http.routers.booklore-secure.rule=Host(`booklore.ahwz.dev`)"
      - "traefik.http.routers.booklore-secure.tls=true"
      - "traefik.http.routers.booklore-secure.tls.certresolver=cloudflare"
      - "traefik.http.routers.booklore-secure.service=booklore"
      - "traefik.http.services.booklore.loadbalancer.server.port=6060"

  mariadb:
    image: lscr.io/linuxserver/mariadb:11.4.5
    container_name: booklore_db
    environment:
      - PUID=${DB_USER_ID}
      - PGID=${DB_GROUP_ID}
      - TZ=${TZ}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    volumes:
      - ~/projects/booklore/mariadb/config:/config
    restart: unless-stopped
    networks:
      - public
    healthcheck:
      test: [ "CMD", "mariadb-admin", "ping", "-h", "localhost" ]
      interval: 5s
      timeout: 5s
      retries: 10

networks:
  public:
    external: true
